### ISSUE TITLE
Times don't match

### ISSUE THREAD

**Issue by adamralph** [brown-bag/brown-bag.github.com#12]
![image](https://cloud.githubusercontent.com/assets/677704/10844393/7865a94a-7eff-11e5-9465-3ab3c733417e.png)

![image](https://cloud.githubusercontent.com/assets/677704/10844397/85216d7c-7eff-11e5-9485-79b73a8e47df.png)

![image](https://cloud.githubusercontent.com/assets/677704/10844406/9bde6a4c-7eff-11e5-8f7b-7bce15398f1b.png)

So in short:

* website: 12:00
* crowdcast: 11:00
* gcal: 12:00

**Comment by gep13** [comment]
Same issue for me.

**Comment by danielmarbach** [comment]
I think that is an issue from crowdcast. They didnt take the time shift into account. I'll fix

**Comment by danielmarbach** [comment]
Unfortunately there is still a big disconnect between crowdcast and the website. I'm working on an automation spike to close the gap. As soon as things settle around the crowdcast changes (they are currently dropping the free version) I make the spike public

**Comment by gep13** [comment]
These are the issues that I saw...

Add to Calendar said this:

![image](https://cloud.githubusercontent.com/assets/1271146/10847173/969faab6-7f0c-11e5-94ba-374a87896abb.png)

And Website said this:

![image](https://cloud.githubusercontent.com/assets/1271146/10847177/9d93f192-7f0c-11e5-99c2-c6d7908a6bd0.png)

I am based on the UK.

Let me know if you need any other details.

**Comment by danielmarbach** [comment]
Crowdcast detects on my machine when I create the sessions Western European Standard Time which is UTC+1 but

![image](https://cloud.githubusercontent.com/assets/174258/10848879/6faa908a-7f1e-11e5-9a97-0a1eec111fc6.png)

So as I supected crowdcast didn't take into account the daylight saving changes. And now it is impossible to change the timezone:

![image](https://cloud.githubusercontent.com/assets/174258/10848937/bbe1e32c-7f1e-11e5-9d87-0fbc9b97aa6e.png)


I'm going to change the event date and time on crowdcast.

**Comment by adamralph** [comment]
@gep13 am I missing something in your screenshots?

gcal = 22:00 and crowcast = 10pm, so it's OK no?

**Comment by danielmarbach** [comment]
Done. Now this is what I see

![image](https://cloud.githubusercontent.com/assets/174258/10848993/f1d2ce4c-7f1e-11e5-8f6e-ed6780cc0d80.png)

![image](https://cloud.githubusercontent.com/assets/174258/10849064/37eb6254-7f1f-11e5-97e5-6158fadd6a38.png)


![image](https://cloud.githubusercontent.com/assets/174258/10849077/4410e61c-7f1f-11e5-8771-ff70bee99b70.png)

Ok now?

**Comment by gep13** [comment]
>@adamralph said...
@gep13 am I missing something in your screenshots?

According to @hmemcpy the talk is at 11am GMT (https://twitter.com/hmemcpy/status/660056218749313024) where as I was getting the event at 10PM.

**Comment by gep13** [comment]
Looks good to me now:

![image](https://cloud.githubusercontent.com/assets/1271146/10849197/717804a8-7f17-11e5-9d28-eb91aee3fc4b.png)

Although on the site, would still be nice to see the time zone, similar to crowdcast site:

![image](https://cloud.githubusercontent.com/assets/1271146/10849221/8f9f3d0c-7f17-11e5-8c43-4ec0d7aea036.png)

But that is small thing.

**Comment by adamralph** [comment]
@gep13 According to @hmemcpy the talk is at 11am GMT 

OK, I understand now.

**Comment by adamralph** [comment]
I've also just noticed that in my original screen shot that crowdcast had the wrong day too, it said Sunday 1st. It must have been interpreting 12pm as 12am, and when going an hour it went to 11pm instead of 11am. Crowdcast obviously has some serious datetime issues.

**Comment by adamralph** [comment]
@danielmarbach I just checked all three and all looks good for me now too.

You're going to love this though - as a test, I changed my time zone to US Central time and got this:

![image](https://cloud.githubusercontent.com/assets/677704/10849352/ad57e67e-7f20-11e5-97a9-69f1af9b94c3.png)

![image](https://cloud.githubusercontent.com/assets/677704/10849358/bb139344-7f20-11e5-9de4-98743336baa5.png)

![image](https://cloud.githubusercontent.com/assets/677704/10849384/dd584422-7f20-11e5-8519-8a13e265a6f2.png)

:sob:

**Comment by adamralph** [comment]
... and this is because the US clocks change on Sunday 1st.

**Comment by danielmarbach** [comment]
@adamralph I cannot influence what crowdcast is doing :(

**Comment by danielmarbach** [comment]
Closing since I cannot influence what crowdcast is doing at the moment
