### ISSUE TITLE
Calendar link is not obvious

### ISSUE THREAD

**Issue by adamralph** [brown-bag/brown-bag.github.com#13]
![image](https://cloud.githubusercontent.com/assets/677704/10844436/d3e97d3c-7eff-11e5-840e-870b817da21b.png)

The link to add a calendar entry is not very obvious. The icon isn't very prominent and doesn't draw the user toward it. I propose:

* User a more obvious icon/button, e.g. https://addtocalendar.com/
* Move the button to the right of the text

E.g.

![image](https://cloud.githubusercontent.com/assets/677704/10844538/a55a768c-7f00-11e5-8874-bf02a17af2f6.png)

**Comment by gep13** [comment]
:+1:

**Comment by danielmarbach** [comment]
Would a better icon on the left also do the job?

**Comment by adamralph** [comment]
For some reason my eye (and muscle memory) expects it on the right. I find myself instinctively mousing towards the time when looking for something to click.

In fact, I always forget what to click and try and click the entire date and time text before remembering that it's just the icon.

On the right would also match the social media links next to the presenter name:

![image](https://cloud.githubusercontent.com/assets/677704/10848845/35a37690-7f1e-11e5-950a-f6331ce15b60.png)

seems more natural than

![image](https://cloud.githubusercontent.com/assets/677704/10848868/5d68acae-7f1e-11e5-859c-e5551a192848.png)

But if you prefer it on the left, that's still a big improvement.

**Comment by danielmarbach** [comment]
Good points! I'll send in a PR and some screenshots

**Comment by danielmarbach** [comment]
@adamralph what about this?

![image](https://cloud.githubusercontent.com/assets/174258/10849406/eff4a364-7f20-11e5-9a7c-5a94828013a4.png)

**Comment by danielmarbach** [comment]
This time with more spacing

![image](https://cloud.githubusercontent.com/assets/174258/10849436/0c2a0074-7f21-11e5-8705-be0473a1fc46.png)

**Comment by adamralph** [comment]
@danielmarbach looks good. I'd probably expect the button text to bottom align with the date time text, or perhaps the button centre just needs to align with the date time text centre.

Only other observation is that the other buttons on the page are styled as filled rather than outline, e.g.

![image](https://cloud.githubusercontent.com/assets/677704/10849595/76b9296a-7eef-11e5-96d7-f466f574065c.png)

I'm not sure if the calendar button should match this styling or not. I'm certainly no design expert :stuck_out_tongue_closed_eyes:.

Perhaps we could hit up @sergioc for some advice?

**Comment by danielmarbach** [comment]
It doesn't have to be perfect just yet ;)

**Comment by danielmarbach** [comment]
I would like to keep the Add to calendar button different from the Attend this session, Watch recording... buttons below

**Comment by danielmarbach** [comment]
@adamralph Aligned the button and merged

**Comment by adamralph** [comment]
@danielmarbach :+1: looks good!

**Comment by gep13** [comment]
@adamralph thanks for your speedy help on this! :smile:
