### ISSUE TITLE
Suggestion: Show original date/time and timezone of each session

### ISSUE THREAD

**Issue by caioproiete** [brown-bag/brown-bag.github.com#18]
Hello,

I'd like to suggest you always show the original date/time and timezone of each session instead of trying to localize the time to the current timezone of the user.

Several reasons why I think it makes sense:
- Just because I'm in timezone X right now, doesn't mean I'll still be in timezone X on the day of the session. When deciding to attend or not, I need to know which time it will be in the timezone of the place where I'll be in the future
- Not including the original timezone when I add to the calendar will fix it to whatever timezone I am in at the moment, and will not adjust to any DST changes that may occur in the original timezone between now and the day of the session. 
- It can be quite confusing. I visited the site whilst connected through a VPN in the US (UTC-6), saw a session that started at 5am in the morning. A few hours later I came back to the site without using the VPN so it picked up my current timezone (UTC-4), and of course now it shows 7am. I got so confused I had to check the source code of the site to see what was going on and spot the moment.js conversion.

---

Happy to send a PR if needed.

**Comment by danielmarbach** [comment]
Hi,

Thanks for that suggestion. In my humble opinion we would be improving the site for a minority of our user base. Most of our users will lickely not switch the timezones like you do. The cognitive overhead to do the necessary calculations in their heads everytime they look at the UTC date including the time offset is probably too high. Of course I'm willing to be convinced otherwise. 

Another possible solution would be to have two dates. The original time and the localized one. The problem is that approach could also be quite discracting from a usability point of view.

**Comment by caioproiete** [comment]
Hi @danielmarbach,

That's odd. You're assuming that only a minority of developers travel? That's not what I see... Especially in the US where devs travel all the time (and I'm not from the US).

Anyway, forget about traveling. Look at point number 2. Should be enough reason to change.

---

The users should not have to do any calculation in their heads... There's lots of services on the internet that do this for you. All you have to do is add a hyperlink to one of these services close to the date/time of the event.

Here is an example I just did using the [Event Time Announcer](http://www.timeanddate.com/worldclock/fixedform.html) from timeanddate.com.

[![image](https://cloud.githubusercontent.com/assets/177608/11169972/f76b7978-8b9c-11e5-83b2-2b7d008946e0.png)](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Introduction+to+Visual+Studio+Extensibility+Demystifying+the+art+of+creating+extensions+for+Visua...&iso=20161118T12&p1=3903&ah=1)

http://www.timeanddate.com/worldclock/fixedtime.html?msg=Introduction+to+Visual+Studio+Extensibility+Demystifying+the+art+of+creating+extensions+for+Visua...&iso=20161118T12&p1=3903&ah=1

---

Also, have you ever seen any virtual conference that doesn't show you the original time and timezone?
That is what people are used to...

**Microsot Connet(); 2015**
http://connect2015.visualstudio.com
[![image](https://cloud.githubusercontent.com/assets/177608/11170031/c3e3543e-8b9e-11e5-86b7-b52b69114e5e.png)](http://connect2015.visualstudio.com)

**Office 365 Developer camp in Belgium**
https://msevents.microsoft.com/CUI/EventDetail.aspx?EventID=1032643183&Culture=en-BE&community=0
[![image](https://cloud.githubusercontent.com/assets/177608/11170003/cb04d590-8b9d-11e5-80a4-40b20c8408b4.png)](https://msevents.microsoft.com/CUI/EventDetail.aspx?EventID=1032643183&Culture=en-BE&community=0)

**Educase Virtual Conference 2015**
http://www.educause.edu/annual-conference/agenda-and-program/virtual-conference-agenda
[![image](https://cloud.githubusercontent.com/assets/177608/11170012/1c9d4612-8b9e-11e5-9463-66761586d76f.png)](http://www.educause.edu/annual-conference/agenda-and-program/virtual-conference-agenda)
